# dart run ffigen --config ffigen_config.yaml

# config for generating bass.dart
 output: 'lib/src/bass/bass.dart'
 headers:
   entry-points:
     - 'BASS/bass.h'
 name: 'Bass'

# config for generating bass_wasapi.dart
# output: 'bass_wasapi.g.dart'
# headers:
#   entry-points:
#     - 'BASS/basswasapi.h'
# name: 'BassWasapi'