[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.3.0"
lofty = "0.21.1"
serde_json = "1.0.117"
phf = { version = "0.11", features = ["macros"] }
anyhow = "1.0.86"
image = "0.25.2"
